apiVersion: v1
kind: Service
metadata:
  name: vi-service
spec:
  type: NodePort
  selector:
    app: vi
  ports:
    - protocol: TCP
      port: 5000            # Service port
      targetPort: 5000      # Matches container port
      nodePort: 30200       # Expose the Service on this port on each Node
